### PR TITLE
Teabag -> Teaspoon

### PR DESCRIPTION
**Pull request by jayzes**
@jejacks0n anything else I'm missing on the conversion here?

### CODE REVIEW

**Comment by jedschneider** [comment]
@jayzes its already done on the rails-3-stable branch. https://github.com/modeset/cmsimple/commit/76376eb63b3dd031a986f8cd4eec664f27697a3f

**Comment by jedschneider** [comment]
the reason its not in master is because I was hoping to make master rails-4 compatible...

**Comment by jedschneider** [comment]
see the rails-4-rebase branch for that.

**Comment by jayzes** [comment]
We should probably update the readme with that - there are a bunch of rails3 projects we have that are currently pointed just at master.

MODE SET.
_  

jay zeschin
director. developer.

720.273.9549
modeset.com (http://www.modeset.com)

**Pull request closed without merging**
